global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: classifier_g4
    static_configs:
      - targets: ['classifier-g4.calmstone-d77b2aac.westeurope.azurecontainerapps.io']